apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .service_name }}-configmap
  namespace: {{ $.Release.Namespace }}
data:
  LOG_LEVEL: {{ .log_level | quote }}
  LOG_FORMAT: {{ .log_format | quote }}

  PORT: {{ .port | quote }}

  OPENAPI_PATH: {{ .openapi_path | quote }}
  OPENAPI_FILE_NAME: {{ .openapi_file_name | quote }}